on:
  push:
    branches:
      - src-pages


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: src-pages
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /src/dist/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: /src/assets/scss/index.scss
          destination: /src/dist/css/index.css

      - name: Upload Complied CSS
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Compiled-CSS
          path: /src/dist/css
